import { Inter } from "next/font/google";
import './globals.css';
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Provider from "@/component/Provider";
import UserContextProvider from "@/context/UserContextProvider";
import ConditionalNav from "@/component/CondiatinalNav";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContextProvider>
        <Provider>
        <ToastContainer/>
            <ConditionalNav/>

            {children}
          </Provider>
        </UserContextProvider>
    
      </body>
    </html>
  );
}
